// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectIS2.Contexts;

#nullable disable

namespace ProiectIS2.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102222058_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProiectIS2.Models.Facts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fact")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)");

                    b.Property<bool>("SpecialType")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("CatFacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fact = "On average, cats spend 2/3 of every day sleeping. That means a nine-year-old cat has been awake for only three years of its life.",
                            SpecialType = true
                        },
                        new
                        {
                            Id = 2,
                            Fact = "Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.",
                            SpecialType = false
                        },
                        new
                        {
                            Id = 3,
                            Fact = "When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.",
                            SpecialType = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
